name: Pastdown
options:
  bundleIdPrefix: com.pastdown
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"

targets:
  Pastdown:
    type: application
    platform: macOS
    sources:
      - path: Pastdown
        excludes:
          - Resources/Assets.xcassets/MenuBarIcon.imageset/menubar_icon.pdf
    resources:
      - path: Pastdown/Resources/Assets.xcassets
    info:
      path: Pastdown/Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: Pastdown
        CFBundleName: Pastdown
        LSApplicationCategoryType: public.app-category.utilities
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pastdown.app
        PRODUCT_NAME: Pastdown
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: Pastdown/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: false
        CODE_SIGN_STYLE: Manual
        SWIFT_STRICT_CONCURRENCY: minimal
    dependencies:
      - package: GRDB
        product: GRDB
    entitlements:
      path: Pastdown/Pastdown.entitlements
      properties:
        com.apple.security.app-sandbox: true
